---
title: TrueCoders
timezone: America/Chicago
collections:
  classes:
    title: Classes
    output: false
  coders:
    title: Coders
    output: true
  courses:
    title: Courses
    output: true
  employers:
    title: Employers
    output: true
  faqs:
    title: FAQs
    output: false
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  subjects:
    title: Subjects
    output: false
  team:
    title: Team
    output: false
defaults:
- scope:
    path: ''
    type: coders
  values:
    layout: resume
    subtitle: 
    image: 
    class: 
    profiles:
      mbti: 
      github: 
      linkedin: 
      codewars: 
      vimeo_resume: 
    skills:
    - name: 
      level: 3
    work:
    - company: 
      job_title: 
      start_date: 
      end_date: 
      location: 
      body: 
    education:
    - institution: 
      area: 
      start_date: 
      end_date: 
      gpa: 
      location: 
      body: 
- scope:
    path: ''
    type: courses
  values:
    layout: course
- scope:
    path: ''
    type: employers
  values:
    layout: page
- scope:
    path: ''
    type: sections
  values:
    display_title: 
    subtitle: 
    sub_collection: 
    limit: 3
    call_to_action:
      title: 
      url: 
    subsections:
    - title: 
      subtitle: 
      fa_icon: 
      body: 
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: team
  values:
    layout: page
- scope:
    path: ''
    type: pages
  values:
    layout: page
    display_title: 
    subtitle: 
    menus:
      is_nav: false
      is_footer: false
    hero:
      color: "#0093c9"
      image: 
    sections:
    - 
    call_to_action:
      title: 
      url: 
      body: 
- scope:
    path: about.md
    type: pages
  values:
    layout: collection-page
    collection: team
- scope:
    path: courses.md
    type: pages
  values:
    layout: collection-page
    collection: courses
- scope:
    path: employers.md
    type: pages
  values:
    layout: collection-page
    collection: employers
- scope:
    path: coders.md
    type: pages
  values:
    layout: collection-page
    collection: coders
- scope:
    path: contact.md
    type: pages
  values:
    layout: contact
- scope:
    path: faqs.md
    type: pages
  values:
    layout: faqs
- scope:
    path: hire.md
    type: pages
  values:
    layout: hire
- scope:
    path: index.md
    type: pages
  values:
    layout: index
    hero:
      call_to_action:
        title: 
        url: 
description: |-
  Be Mentored. Be Connected.

  We believe that smart, passionate people should always be engaged, doing what they love to do. Our mission is to educate smart, passionate people as they become skilled developers, to keep them engaged working with companies solving real-world problems, and to continue mentoring them as they grow their skill set.
author:
  name: TrueCoders
  twitter: truecodersio
image: "/uploads/logo.png"
logo: "/uploads/logo.png"
social:
  name: TrueCoders
  links:
  - https://twitter.com/truecodersio
  - https://www.facebook.com/truecodersio
  - https://www.linkedin.com/in/truecodersio
  - https://github.com/truecodersio
twitter:
  username: truecodersio
sass:
  style: compressed
url: https://truecoders.io
baseurl: 
kramdown:
  show_warnings: true
liquid:
  error_mode: strict
permalink: pretty
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
safe: true
strict_front_matter: true
